name: Bug Report
description: Report unexpected behavior or crashes
title: "[BUG] "
labels: ["bug-report", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I've checked existing issues and pull requests
          required: true
        - label: I've read the [Code of Conduct](https://github.com/FlakySL/translatable/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Are you using the latest translatable version?
          required: true

  - type: dropdown
    attributes:
      label: Component
      options:
        - Core library
        - Macros crate
        - Documentation
    validations:
      required: true

  - type: input
    attributes:
      label: Rust Version
      placeholder: Output of `rustc --version`
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Step-by-step instructions to reproduce the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected vs Actual Behavior
      description: What you expected to happen vs what actually happened

  - type: textarea
    attributes:
      label: Additional Context
      description: Logs, screenshots, or code samples
