name: Bug Report
description: Report unexpected behavior or crashes
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: checkboxes
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I've checked existing issues and pull requests
          required: true
        - label: I've read the [Code of Conduct](https://www.rust-lang.org/policies/code-of-conduct)
          required: true

  - type: dropdown
    attributes:
      label: Component
      options:
        - Core library
        - Macros crate
        - Documentation
        - CI/CD
    validations:
      required: true

  - type: input
    attributes:
      label: Translatable Version
      placeholder: 0.x.x
    validations:
      required: true

  - type: input
    attributes:
      label: Rust Version
      placeholder: Output of `rustc -V`
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      description: Step-by-step instructions to reproduce the issue
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected vs Actual Behavior
      description: What you expected to happen vs what actually happened

  - type: textarea
    attributes:
      label: Additional Context
      description: Logs, screenshots, or code samples
