blank_issues_enabled: false

contact_links:
  - name: "💬 Community Help (Discord)"
    url: https://discord.gg/AJWFyps23a
    about: |
      For general questions, discussion, or brainstorming:
      - Get real-time help from maintainers
      - Discuss potential features
      - Chat with other contributors
      *Please check existing issues first!*

  - name: "⚖️ Code of Conduct"
    url: https://github.com/FlakySL/translatable/blob/main/CODE_OF_CONDUCT.md
    about: |
      All community interactions must follow the project
      code of conduct, which is based on the contributor covenant.
      *Required reading before participating*

  - name: "🚨 Moderation Contact"
    url: mailto:moderation@flaky.es
    about: |
      For urgent moderation issues:
      - Code of Conduct violations
      - Community safety concerns
      - Escalation requests
