name: PR Coverage check

on:
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up Rust
        uses: actions-rs/toolchain@v1

      - name: Install cargo-llvm-cov
        run: |
          cargo install cargo-llvm-cov
          rustup component add llvm-tools-preview

      - name: Generate Coverage Report
        run: |
          cargo llvm-cov --workspace --lcov > coverage.lcov -- --nocapture --test-threads=1 --color=always

      - name: Fail if overall coverage is below 80%
        run: |
          apt-get install lcov -y

          coverage_percentage=$(lcov --summary coverage.lcov | grep "lines:" | awk '{print $2}' | sed 's/%//')

          echo "Coverage Percentage: $coverage_percentage%"

          if (( $(echo "$coverage_percentage < 80" | bc -l) )); then
            echo "Coverage is below 80%. Failing the build."
            exit 1
          else
            echo "Coverage is above 80%. Continuing."
            exit 0
          fi
